name: ESLint Basic Check

on:
  push:
    branches: [ "main", "pipelinetesting", "eslint" ]
  pull_request:
    branches: [ "main", "pipelinetesting", "eslint" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install ESLint
        run: npm install eslint

      - name: Run ESLint
        run: npx eslint . --ext .js
