# .github/workflows/frontend-quality.yml
name: Front-end Quality Checks

on:
  push:
    branches: [ "main", "Somto-Implement-Mini-Game-RPS" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '22 21 * * 3'

jobs:
  proof-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: anishathalye/proof-html@v2.2.0
        with:
          directory: .
          check_html: true
          check_css:  true
          check_favicon: false

  eslint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18

   
      - name: Install project dependencies (if any)
        id: install-deps
        run: |
          if [ -f package-lock.json ] || [ -f npm-shrinkwrap.json ]; then
            echo "Using npm ci"
            npm ci
          elif [ -f package.json ]; then
            echo "Using npm install"
            npm install
          else
            echo "No package.json – skipping"
          fi

    
      - name: Install ESLint + SARIF formatter
        run: |
          npm install --no-save eslint@8.10.0 \
            @microsoft/eslint-formatter-sarif@3.1.0

    
      - name: Run ESLint and create SARIF
        run: |
          npx eslint . \
            --ext .js \
            --config .eslintrc.json \
            --format @microsoft/eslint-formatter-sarif \
            --output-file eslint-results.sarif \
          || true                          

     
      - name: Upload SARIF to Security tab
        if: hashFiles('eslint-results.sarif') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: eslint-results.sarif
          wait-for-processing: true
